version: "3.8"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
  celery:
    build: .
    command: celery -A app.tasks worker --loglevel=info -c 4
    env_file:
      - .env
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    env_file:
      - .env
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: Password123!
      POSTGRES_DB: image_similarity
    ports:
      - "5432:5432"
    env_file:
      - .env
