services:
  web:
    image: image-similarity:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  celery:
    image: image-similarity:latest
    command: celery -A app.tasks worker --loglevel=info -c 4
    env_file:
      - .env
    depends_on:
      - db
      - redis

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    env_file:
      - .env
    restart: always

  db:
    image: image-similarity-db:latest
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: Password123!
      POSTGRES_DB: image_similarity
    ports:
      - "5433:5432"
    env_file:
      - .env
    restart: always