services:
  web:
    image: image-similarity:latest
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./temp:/app/temp
      - ./temp_catalogue:/app/temp_catalogue:rw
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  celery:
    image: image-similarity:latest
    command: celery -A app.tasks worker --loglevel=info -c 4
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./temp:/app/temp
      - ./temp_catalogue:/app/temp_catalogue:rw
    depends_on:
      - db
      - redis

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    env_file:
      - .env
    restart: always

  db:
    image: ankane/pgvector
    environment:
      DB_NAME: image_similarity
      DB_USER: testuser
      DB_PASSWORD: Password123
      POSTGRES_PASSWORD: Password123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - image_similarity_db:/opt/postgres-servers/image-similarity
    restart: always

volumes:
  image_similarity_db: