services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  celery:
    build:
      context: .
    command: celery -A app.tasks worker --loglevel=info -c 4
    env_file:
      - .env
    depends_on:
      - db
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    env_file:
      - .env
    restart: always

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: Password123!
      POSTGRES_DB: image_similarity
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: always